language: java
matrix:
  include:
  - os: linux
    dist: bionic
    jdk: oraclejdk11
    addons:
      apt:
        packages:
        - libgtk-3-dev
  - os: osx
    osx_image: xcode11
    jdk: oraclejdk11
script:
- "./gradlew build"
after_success:
- |
  case "${TRAVIS_OS_NAME}" in
    osx)   export TARGET=macosx ;;
    linux) export TARGET=linux ;;
    *)     exit 1 ;;
  esac
- cp build/bin/libui/releaseExecutable/hello-libui.kexe demo-${TARGET}.kexe
deploy:
  provider: releases
  api_key:
    secure: aAn+yZNOCTe8aub3LzhoD/pfnv2YzxibWpLUr2bQ7C9mTWdIVoJ4O2e3fbQQL2EM4SHeilvZS/1hNPtL3bCyJo8+ibySMsiBNBkBuL83wyD5XiA102oOHMNfnqblyVqBoQJii3bTEaJjWfsgbXqxAWf/ax97kBA+kInGp8YjAQTjft5VDqj1YBOzdJdZQH0JjynK3ufrq439cMTRhppInEo1DKCHfB/xV/N6/F3vlJfaDsDtkWoLit4IJ92EdP2OgAGWMdHs9P9Uf8OlSwz4/Q99wGK6JTs60TJRp9DX+rG1pLcHrquIzbd2L7BN5e9BTL7SKwmJz/nwCAjJXd6UveqqnFIaCzmyKgWIxoULovmiQ9mQMEd91BODi0sqHHfF6vH0DAZ3cyS819D37Eby04LpUqspCFTJ69zsqOzslDNO05EfAFo2tbPJPi+lKCcNpus8U0oIPc4tXIIVA85TKVlMAT8XC+wPY9nLPfMXqg/TpEMm6FgPexLELPohwEepOsPDkWLJx7azG9U70sURQE3hq9yYuerBH71gmy6jeTXKsg+jK23Cz6HEPBxJw3TfvMdmK1Sx1usBDuzg+G2aVWxuO7Hmgh/HTNc3lvBHBtEQWGLwwrmXXejlenfY3ri/u6VLMl23LrzvAqaI95xtO8FoBy1QgcTvsO+ZRPmk5sk=
  file_glob: true
  file: demo-*.kexe
  on:
    tags: true
    repo: wuseal/hello-libui
