language: java

matrix:
  include:
    - os: linux
      dist: bionic
      jdk: oraclejdk11
      addons:
        apt:
          packages:
            - libgtk-3-dev
    - os: osx
      osx_image: xcode11
      jdk: oraclejdk11

script:
  - ./gradlew build

after_success:
  - |
    if [[ "x${TRAVIS_TAG}" != "x" ]]
    then
      ./gradlew -PpublishMode -PBINTRAY_REPO=kotlin-native -PVERSION_SUFFIX publish
    else
      ./gradlew -PpublishMode -PBINTRAY_REPO=kotlin-dev -PVERSION_SUFFIX=-dev publish
    fi
  - |
    case "${TRAVIS_OS_NAME}" in
      osx)   export TARGET=macosx ;;
      linux) export TARGET=linux ;;
      *)     exit 1 ;;
    esac
  - cp /build/bin/libui/releaseExecutable/hello-libui-master.kexe demo-${TARGET}.kexe
  
deploy:
- provider: releases
  api_key:
    secure: frR7XL8Swlf15oVCDU1/+zY/uANwUfx7mhiX3zGKH8VXN3zi+sZrPMhNwniSGAcUt9rhCOQwi/f2dBFinNcJrNlr9alLRVbk67Gvif/L0GW2Okb62W8fCz2M9ekLkrQ+1i8d4lKkUbMRw/RvNTtiROPF8YrBzb58LeqF6nm/ZrMVAzdWhFrlxsjN+SUqKps+Rc/IPjixwazlmrZUmBeOduQUiCS/7J7A8A25rnTiAMaNj4UDmPIYbJUKtcZnZeFwELma68BBDgEw3CJB7h3sSXNv+d25E+dHukFvGbhRtMHhSO5O9lCZjkyD6gE1sjRzpg3eamtayDGVcaGJYBQ63W1/InER+TK3Veh1Exauyhj1Doi/8n9CBHiE0xvGe/r+r0nflBegDhAkIX3ZNLyuKVIkvjt6ELq6+pEYGzrIYaFgSKoS5laXU4FlmZ2sQebCWBrg8mFjEaZLoSCFgtmN3l98ewXAxdTIGss4KXYBo7Xb20VO6FRCclHPPMX1KR5nK7Zt0J8gAx9rVqiUKL9h3TWDeODdVwewzrv/YsDf6YMegEq2vGZ628+4S32smGqjYI385zRiqstkhuEmlDub0ll+3vdAgCzotljARNX/aUeI8t94liE4a6OdWJn+LsCYlxJvby8kBFrj10JOpWpC54kGldaAOThDqeGrJgaYp+8=
  file_glob: true
  file: demo-*.kexe
  skip_cleanup: true
  on:
    tags: true
    repo: wuseal/hello-libui
