language: java
matrix:
  include:
  - os: linux
    dist: bionic
    jdk: oraclejdk11
    addons:
      apt:
        packages:
        - libgtk-3-dev
  - os: osx
    osx_image: xcode11
    jdk: oraclejdk11
script:
- "./gradlew build"
after_success:
- |
  case "${TRAVIS_OS_NAME}" in
    osx)   export TARGET=macosx ;;
    linux) export TARGET=linux ;;
    *)     exit 1 ;;
  esac
- cp build/bin/libui/releaseExecutable/hello-libui.kexe demo-${TARGET}.kexe
deploy:
  - provider: releases
    api_key:
      secure: j4u4BrsOsjXo8ravU4V1n4Mn2itPUDsgGOAXth8SRuwUH00VaKpHf7HGV/lTOIfeoKhCKVq3sIEXbaqNzC2GdPIqhzSRLj2l174lExaDifLi1lLrgseyYeb9mB6q7/l/pbBD98mh9O4alK/Mz/JG246/J6+klJ0g9es/bnbAZzz7pQV0SEoRj9ZiEiyklCrTkfDclS+LIJ7Lcy75TdjbP0eyVyq8VqXEJWcjaElYiwxlf/NU9rTViB82Ygcj0tb7UkpaaXZrQY45PdzlW+Wrq92ASXfYqry35+I4Gx8mLPsNjksQ+yS1byWSRtimYqf788A4aLViR10hExi6xvMkghYjlTFB8XvNjqbbgPdPt/juch2KcyRXKVRhxnrCsSxk4E9PMAmLVZyXdK/SMaxClrgSNJ4CVjCqmWF1qPnR5yAB8v0HIqxe6lnWP8so2CAv7D/1LZrh9pXApt9tfzA7R+ymEK5gi33DBCiznpPR2izIjPto8rFO0wp+paws+HJJi+dOS18aVKJdZ0d5D64DclOSp5FCEfvyJ4duwbr/3w4uOlasGwmH5Oi+c/LpewXFzoomq0//ZN61QMo7iZdfLcqoWxF0woszOJRb4YcMws51ctPcrguIrRDb5qalHFfflaIDcM8b5Sg8MeDFuBRmTsUcbzDg76TYcqjJTQPYsC0=
    file: demo-*.kexe
    skip_cleanup: true
    on:
      tags: true
      repo: wuseal/hello-libui
env:
  global:
    - secure: X2HfosZUVNjNFZ3hSDFuSc9b7Ari1a6kqj1NO0xXUv7Y4nTgbdfNBODE7HUHIFMQkwQ+AL6MpYKbxzXdcsj0w8lPOJnX7IDVk1UwwrDAyN51/a8BWbsK+sgvRMZn4hzYw6Wo+CqpVQPG0ZNf1dX54ri5J90xXZGb53Li/WcsqZbzUk7Q8Nr1QHLzkeJN1QyhbPr6WHWqjILTIgeWk543IzGtnZXErptBpfdiXN9AkipBYz+pqVP3J1NQQtfbXYu2B1ERYxY6BXlRBheNXXPD/hcClhDqcBWi8MV6iXcID+W4yhRAYgVS8eqMd3tVEEliM0N1M6KloM9xuyzMtnrYcICppHl4IxkXK6rWTWHIqiQ7qlXPMUyZY4+mWlk4aeiOjJ2ye3lwH7Yjt/NRX5utApS8tB8R5l2+HCOOuneBO/t7w9l4HKOXOxxnpyUSKBoIOUCf0a6/SzTNCG331s7gazrwVyN2Ed5H/lV2iYZ8nVwgv8VxLI00I2zNpqfna8EphXokv6Kahhr6FxyRE3UyJZyCYLSy65pFaQSOA4Rx0epo5a7AXZ/nK5Kvu7UBxkGnLIwx0dcOnbo5K1QOhloWoJ4NWe5yrVaCVE2zPcLMsdsk9iPH3a9e5+YJJNAwiaLyKH0PXLX7COMSw4NPY3+VqWmk9IPG3q8b7ZEYeFMtLt4=