language: java

matrix:
  include:
    - os: linux
      dist: bionic
      jdk: oraclejdk11
      addons:
        apt:
          packages:
            - libgtk-3-dev
    - os: osx
      osx_image: xcode11
      jdk: oraclejdk11

script:
  - ./gradlew build

after_success:
  - |
    case "${TRAVIS_OS_NAME}" in
      osx)   export TARGET=macosx ;;
      linux) export TARGET=linux ;;
      *)     exit 1 ;;
    esac
  - cp /build/bin/libui/releaseExecutable/hello-libui-master.kexe demo-${TARGET}.kexe
  
deploy:
- provider: releases
  api_key:
    secure: KEPHCjDrXTBOXmCJdCEItv9axsUr6PmjkGLKevXnf5rjbfTdT0ZQkNjjKZnCk18AfKCMKp7KvWkWoVfVZJE5P+dCJ+HWXdMOpUUeQA5ARiE21e+/L3+92k8fRsiyP80GFDqevwk7vdFEo4/pCUq/lGA8fZfWSxm6vRaARf/sMu0OmSU0A6XP25hn/vAJlreURT5bFGukPR4tfcnXWxFM9F8/IDqjX0vo+Q/WxwxTljE/WFMZgZs33C3QbRScKrlHgD9CnwvViuzTAMWXwYsXiMeklXG2Z6M7P9FuRrfZlYEOcQq/VkkpYw3rO/sympwYBppD78Sz7/iLNSAgaRW/3YGiFbssfYz2baf99Xv9uSdwynj+1ci7aCh3Oqy8vUShe2NVzEDsdYEJpu2iRQQmyMkzjvOCkUwntPQ8SChCjGnwsXtuBscY97VS26EVzqyzObmZEGjpiocshM+qo35R7MOEAH65KNG9lBzsulX3BuIt34x9clngXd3t6Hlj9LM66zVUmsALk+gvmYzjZxJYNo03miBypAb+YSHc8dWxLaug3oDrKF/ZxOYRuS4ZUyMTcab+qCiZOVWfV07j6DU6iJe1F/6FDBh/lMYkSCWfCdPqXij1l8UP7A18ej/zh3guhPFVZkMZjne3SGm1pLWfL459fjoTB/qWnqyPrJrpavA=
  file_glob: true
  file: demo-*.kexe
  skip_cleanup: true
  on:
    tags: true
    repo: wuseal/hello-libui
