language: java
matrix:
  include:
  - os: linux
    dist: bionic
    jdk: oraclejdk11
    addons:
      apt:
        packages:
        - libgtk-3-dev
  - os: osx
    osx_image: xcode11
    jdk: oraclejdk11
script:
- "./gradlew build"
after_success:
- |
  case "${TRAVIS_OS_NAME}" in
    osx)   export TARGET=macosx ;;
    linux) export TARGET=linux ;;
    *)     exit 1 ;;
  esac
- cp build/bin/libui/releaseExecutable/hello-libui.kexe demo-${TARGET}.kexe
deploy:
  matrix:
  - provider: releases
    user: wuseal
    file_glob: true
    file: demo-*.kexe
    skip_cleanup: true
    on:
      tags: true
      repo: wuseal/hello-libui
  password:
    secure: bv1lQ5TnsBdp8ZM3cYgiEGRW92a2WSsZG+WAGO6PONCTltyMlxrcu6DHu0RfdG0w3TuAkBt3yro+fvg7IT0Up0yIwEN1sEKDaYaJ880jfiSLtaihHo9su+SqzBvqCRAu4ryAnpQXKd7JVI2eqrJJjJ1WhNcPh30cjQw8Elsz0c2FeCbFCCm9wv+kPpGqemj+Q45zikWE8BCTo07SbOpEmpa2FJvZt8yPJ3wHdFjtAP1959bz0X2yH4fpqn2InHmhOKfuB1VXxsVlD3nZOoi9F7ywm2XCKbPuFH/99Pa9sQNwR8WAS0aGFvk0BNm0noLoapg5vznRXjc4TplgVol9c2Y0eyGPJbDI1O9xCxtcHljrHWgPuvOIicDO4/Pl7Kr9P9utXx9hiAZ6MxABZCjmpcr3ANI4zY63xgraY0wDYC0J/oftIlxnrZzIlV5G+OvUI4rypnA7SeuU9caItMgAjaCQ2QjYB2Q9UEjLNW7KnA755U3MZA11MoiJSXdv/SyupS5BsSeXOBeIpoRAis6Gf+XXngIB63q9biezbYtpSP/LrJT6MSCmMaDu/XSEOMeD/MfJ3xZkWv4ttjI5fYtXQvCy8HILhFrJ5L3Qbme5pzQOw+LdrcEpMa3TZcWr3xxVCVV2aGZGSyRR8fMZSZ3b52wK1nmA22CQqDIa/ObcSAo=
