language: java

matrix:
  include:
    - os: linux
      dist: bionic
      jdk: oraclejdk11
      addons:
        apt:
          packages:
            - libgtk-3-dev
    - os: osx
      osx_image: xcode11
      jdk: oraclejdk11

script:
  - ./gradlew build

after_success:
  - |
    if [[ "x${TRAVIS_TAG}" != "x" ]]
    then
      ./gradlew -PpublishMode -PBINTRAY_REPO=kotlin-native -PVERSION_SUFFIX publish
    else
      ./gradlew -PpublishMode -PBINTRAY_REPO=kotlin-dev -PVERSION_SUFFIX=-dev publish
    fi
  - |
    case "${TRAVIS_OS_NAME}" in
      osx)   export TARGET=macosx ;;
      linux) export TARGET=linux ;;
      *)     exit 1 ;;
    esac
  - cp /build/bin/libui/releaseExecutable/hello-libui-master.kexe demo-${TARGET}.kexe
  
deploy:
- provider: releases
  api_key:
    secure: NVfoiuig3+2pLZu0LZdxCrNtUqe5/Xayx7jKL69VND7ZoGCmS3laJ9ZXf5nD3bzrrn+IH/jCroOL8SKARsw2YgeSqm5CT221HJGeBWzCmAOrNK6tw/y1Y5l9XraessdqC8Nkl1gHwjtaNxMVZz7TFjIy9uSpq3ptUKWaqkZnzXNw42rqAl8SwbJkzj/Jc30a6MGdlsTelWWRkj7doq65qqo16DMjpK/UASrb442ST5guXfMoGeyyidGmmmyDSAzh1nAICjMRYP0dpH4de2caWjd/l2ku3Ja5ye3IEYDJDa75wo6PEm2gfCqsX1uQmMmhlwa7MnfpWuM3s4KS3zHUf76DbybxRXkjHk1yV5pjyNq0KNSZKPfT0WRtOwPhY/xkwiY+5uHN94l39fPjZCJNehrGAVFdP3pTge/ULyG7u4SSSp3wIG4gNdUmNmYIu20W8gS2Dvh+UCGN4ZGjeKBBfzUQ4a1oUMCgbNG7V9P45n7S8JSMl/dBAq6nnnLPHkkJJDusz9C77DJ7o2rosv3NDZ9Lzzm592lqXjJuB65OXowsGiuyfOGTp08X7V5xkZ95QU1tEnFbaATrm6BNYxKYjlyo62Bi82/4v9VqyxSdGFOHLfTExpBD5E2CMHEYufYBzt3kLpvyy2lWZFCpFE2INBleOoUoiWxZvQmFJO+BeMk=
  file_glob: true
  file: demo-*.kexe
  skip_cleanup: true
  on:
    tags: true
    repo: wuseal/hello-libui
env:
  global:
  - secure: qwrh8fE9lGA3RTzMvV7aA1jN3Hp271GEnSzaWZZIbQeQV36OuZ4S9uYkSIIbVvDZ1uyodh67UOFv7WgmaYkQJmVpW0YjObwfquaLA86ibZaHj7c4SZDXOkVhq1b3Vbhp1G9dCIGDeHmx9OVakmhvEr6ZmuGyskLA0oXS5dDXClUAeINRS9hX7sCZRRVkDl/s2hrqiUINYKEYUyE6eUaIaqCH1NYw5ywxEpaMtobDsxjcttKuspY69ak0rNoUMVVHupS1B5jRpUuMzJc/8YIf0u1MTxg6QIWy+xPWSl1f/NP/PvA1Bx1BcZnTnumemYyn6MG0W6SXIAPLPPHnWmDFnZPls3krk48/HLWd9j/HeMqahG093ZxB9DV1rls+OCgBFmJPdf5A2RznG7afnpMqj/juzyX/qaGfGDkljo6SsPKWHo4ffT7KcGsHB/dM3Gf5qTDqQ3SWuDLqGjZpvvODjM/PSKBsdADpOY85wZnq4nYHm3cQqtMCQOt+Ztr9SXAu3d5YA/+ZUuvdhlQQKJOxn/YcEu3CvrmbBgibCkeL/jJzcePmWidbYmiwBl+ZRVu47y9x8fMWQVn0OELrX64dvAUrXh8cwvDT00R8Hk8mWkpgnB7oSf1+BS9C9KPdWvJIpYpzC/xfXvAu2NOcJj42guv83/EMxWFsM644GDQkwuw=
  - secure: LpbTIpqwuV7QQYoKPxrZ9/sMxDyIqeDOqg3LcOxpZXcGBVD05G88VLiy+moSNzK8p/oCYkc7ky+SzeLBC+lksRQQ4hN1+SJWE5+Uht6woroaD9JvAhfMz49xIr3Cm+PRjN5hIxqUQUXDQ7DiJ5n7Dl4OAAtle6vXZxuJGkx+DOnXR69xEFNTiwpd10mQHEqWhihXOZ2C9egxkZiJRO6kgrJVsUMdfNFMZ84+8s2baXC5tmSTzEauUKiJccoAYEqr5ZDtjY3VIEwmOEufvIyNierv26rlNORGb79zqmHpePCAmsAqCHvFnfdcF4ftw4u9FEF1FXjVrlIMD+RvUqb59QQfd8tyHgUSgCpFJxVtlCB5KLuBMEp1INsfCNrq0nE0FnrUqXCYLQ6iWGyNkmdK4ytIcO+e/JvCHdXjJfpze2AhUzGl89wmtTeHtgKPDGXDJatJ0juJ9qFEqyVMPGfonUuILNfpZjDerGau22nyaAmtpFCuW/VWlDxBSio7TWA7nauzMbLq1T5dHfCmhOEEZkqc5wlXjmtaUTseyEN6u/GgVh/QrXM3z1Pcjz2gkZoXA7mmuGCRRzILoUx3/tPzxigT2o6BH4HMIyLRQSlaA1O0K89Zrs9W0Z48uddiFTJuPGNhe4O2qeCo19sx+6TxBrT3vKaCcFc4JTknjJfgFhI=
